# 테마 설정
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# 내 사이트 정보
title: "Home"
name: "문현규"
description: "연구 블로그"
locale: "ko-KR"

# 메뉴 설정
navigation:
  - title: "Main"
    nav: main

# 사이드바 프로필 설정
author:
  name   : "Hyunkyu Moon (문현규)"
  avatar : "/assets/images/profile/profile.jpg"
  bio    : "Senior Researcher @ KIMM <br> Ph.D. in Mechanical Engineering"
  location: "Daejeon, South Korea"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mhk@kimm.re.kr"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hkmoon88"

# 빌드 설정
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# 기본 레이아웃 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
